# Generated by Django 5.2.4 on 2025-08-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='item_image',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
