# Generated by Django 5.2.4 on 2025-08-09 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_cartitem_total_order_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_items',
            name='order',
        ),
        migrations.CreateModel(
            name='Pending_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(blank=True, max_length=100, unique=True)),
                ('total_cost', models.FloatField()),
                ('proof_of_payment', models.URLField(max_length=500)),
                ('public_id', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_order', to='products.our_user')),
            ],
        ),
        migrations.CreateModel(
            name='Pending_order_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_quantity', models.IntegerField()),
                ('item_price', models.FloatField()),
                ('item_total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_order_item', to='products.pending_order')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Order_items',
        ),
    ]
