# Generated by Django 5.2.4 on 2025-08-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_order_items_order_pending_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_order',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
