# Generated by Django 5.2.4 on 2025-08-10 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_pending_order_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmed_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(blank=True, max_length=100, unique=True)),
                ('total_cost', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_user_order', to='products.our_user')),
            ],
        ),
        migrations.CreateModel(
            name='Confirmed_order_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_quantity', models.IntegerField()),
                ('item_price', models.FloatField()),
                ('item_total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_order_items', to='products.confirmed_order')),
            ],
        ),
    ]
